const {
  Record,
  Component,
} = window.Torus;
const html = window.jdom;

function makeSocialTags({
  twitterUsername,
  url,
  title,
  description,
  imagePath,
}) {
  // combine pieces of image URL and remove potential duplicate // in path
  const imageURL = url.trim() + ('/' + imagePath.trim()).replace(/^\/\//, '/');

  return `<!-- Facebook Open Graph tags -->
    <meta property="og:url" content="${url.trim()}" />
    <meta property="og:title" content="${title.trim()}" />
    <meta property="og:description" content="${description.trim()}" />
    <meta property="og:image" content="${imageURL}" />

    <!-- Twitter Card (large image card) tags -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:creator" content="${twitterUsername.trim()}">
    <meta name="twitter:title" content="${title.trim()}">
    <meta name="twitter:description" content="${description.trim()}" />
    <meta name="twitter:image" content="${imageURL}" />`.split('\n').map(s => s.trim()).join('\n');
}

class App extends Component {
  init(rec) {
    this._selectedByClick = false;

    this.bind(rec, data => this.render(data));
  }
  handleInput(name, evt) {
    this.record.update({ [name]: evt.target.value });
  }
  makeOnInput(name) {
    return this.handleInput.bind(this, name);
  }
  compose(data) {
    const makeInput = name => {
      return html`<div class="inputBlock input-${name}">
        <label class="accent block"
          onclick=${evt => {
            // select the input that comes after
            const inputToSelect = document.querySelector(`.input-${name} input`);
            inputToSelect.setSelectionRange(0, inputToSelect.value.length);
            inputToSelect.focus();
          }}>${LABELS[name]}</label>
        <div class="inputWrapper wrapper block fixed">
          <input type="text" name=${name} value=${data[name]}
            placeholder=${DEFAULTS[name]}
            oninput=${this.makeOnInput(name)} />
        </div>
      </div>`;
    }

    return html`<div class="app">
      <header>
        <h1>Socialite 🍸</h1>
        <p class="description">
          Socialite is a tool I made to generate HTML tags for social sharing
          card metadata (like the ones you see on Twitter and Facebook cards) quickly.
          Yes, the social images for this app are generated by Socialite! To validate
          that they work on your site, use the
          <a href="https://developers.facebook.com/tools/debug/" target="_blank">Open Graph Debugger</a>
          and the
          <a href="https://cards-dev.twitter.com/validator" target="_blank">Twitter Card Validator</a>.
        </p>
      </header>
      <main>
        <div class="formBox">
            ${[
              'twitterUsername',
              'url',
              'title',
              'imagePath',
              'description',
            ].map(name => makeInput(name))}
        </div>
        <div class="downArrow">👇</div>
        <div class="resultBox">
          <label class="resultLabel accent fixed block">Social tags (copy to HTML)</label>
          <div class="textareaWrapper wrapper block fixed">
            <textarea value=${makeSocialTags(data)}
              onclick=${evt => {
                if (this._selectedByClick) return;
                evt.preventDefault();
                this._selectedByClick = true;

                // allow selecting and copying the whole thing on click
                evt.target.setSelectionRange(0, evt.target.value.length);
              }}
              onblur=${() => {
                this._selectedByClick = false;
              }}/>
          </div>
        </div>
      </main>
      <footer>
        <p>
          Socialite is a project by
          <a href="https://thesephist.com/">Linus</a>
          built using
          <a href="https://thesephist.github.io/blocks.css/">blocks.css</a>
          and
          <a href="https://github.com/thesephist/torus">Torus</a>
          on
          <a href="https://replit.com/@thesephist/socialite">Replit</a>.
        </p>
      </footer>
    </div>`;
  }
}

const LABELS = {
  twitterUsername: 'Twitter username',
  url: 'App URL',
  title: 'Social card title',
  description: 'Social card description',
  imagePath: 'Path to social image',
}
const DEFAULTS = {
  // default values, taken from github.com/thesephist/eliza
  twitterUsername: '@thesephist',
  url: 'https://eliza.dotink.co',
  title: 'Eliza: a chatbot written in Ink',
  description: 'Eliza is a simple chatbot written in Ink based on the original ELIZA from MIT AI lab.',
  imagePath: '/img/eliza.jpg',
}
const rec = new Record({...DEFAULTS});

document.body.appendChild(new App(rec).node);
